server:
  port: 8080

eureka:
  instance:
    hostname: discovery-service.int.paas.dev.redhat.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}/eureka/