server:
  port: 8080

eureka:
  instance:
    hostname: https://ads-user-service.int.paas.dev.redhat.com
  client:
    serviceUrl:
      defaultZone: https://discovery-service.int.paas.dev.redhat.com/eureka/
                  
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
