server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: https://discovery-service.int.paas.redhat.com/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
